game: RoadRunnder
step_no: 25000000
seed: no  # randomize if 0 or no

double: no  # != DDQN
prioritized: no

lr: 0.00025
adam_eps: 0.00015
update_freq: 4
epsilon_steps: 1000000
epsilon_end: 0.1  # != DQN
target_update: 10000  # != DQN

learn_start: 80000
mem_size: 1000000
log_freq: 10