game: road_runner
no_gym: yes
step_no: 18750000
seed: no  # randomize if 0 or no

double: no  # != DDQN
prioritized: no

lr: 0.00025
update_freq: 4
epsilon_steps: 1000000
epsilon_end: 0.1  # != DDQN
target_update: 10000  # != DDQN

learn_start: 80000
mem_size: 1000000
log_freq: 1000

test_freq: 500000
test_episodes: 100  # ~500000 frames
test_epsilon: 0.05
