game: road_runner
no_gym: yes
step_no: 25000000
seed: no  # randomize if 0 or no

double: yes  # != DQN
prioritized: no
shared_bias: yes

lr: 0.00025
update_freq: 4
epsilon_steps: 1000000
epsilon_end: 0.01  # != DQN
target_update: 30000  # != DQN

learn_start: 50000
mem_size: 1000000
log_freq: 1000

test_freq: 250000
test_steps: 125000
test_epsilon: 0.001  # != DQN (tuned DDQN)

async_eval: yes
async_update: no
async_memory: yes

mem_device: cuda
pinned_memory: no