game: RoadRunnder
step_no: 25000000
seed: no  # randomize if 0 or no

double: yes  # != DQN
prioritized: yes

lr: 0.00025
adam_eps: 0.00015
update_freq: 4
epsilon_steps: 1000000
epsilon_end: 0.01  # != DQN
target_update: 30000  # != DQN

learn_start: 80000
mem_size: 1000000
log_freq: 100

test_freq: 500000
test_steps: 100000
test_epsilon: 0.001