game: gravitar
no_gym: yes
step_no: 50000000
seed: no  # randomize if 0 or no

double: False
prioritized: False

lr: 0.00025
update_freq: 4
epsilon_steps: 1000000
epsilon_end: 0.1
target_update: 10000

learn_start: 80000
mem_size: 1000000
log_freq: 10

test_freq: 500000
test_episodes: 10
test_epsilon: 0.05
