game: space_invaders
no_gym: yes
step_no: 50000000
seed: no  # randomize if 0 or no

double: no
prioritized: yes
shared_bias: yes
# boot_no: 10
# boot_prob: .5

lr: 0.00025
update_freq: 4
epsilon_steps: 1000000
epsilon_end: 0.1
target_update: 10000

learn_start: 5000
mem_size: 1000000
log_freq: 10

eval_freq: 10000
eval_steps: 2000
eval_epsilon: 0.05

async_eval: yes
async_memory: yes

mem_device: cuda
pinned_memory: no
