game: space_invaders
no_gym: yes
step_no: 50000000
seed: no  # randomize if 0 or no

double: False
prioritized: False
shared_bias: False  # True for tuned DDQN / PER

lr: 0.00025
update_freq: 4
epsilon_steps: 1000000
epsilon_end: 0.1
target_update: 10000

learn_start: 50000
mem_size: 1000000
log_freq: 10

test_freq: 100000
test_steps: 125000
test_epsilon: 0.05

async_eval: yes
async_update: no
async_memory: yes

mem_device: cuda
pinned_memory: no