game: pong
no_gym: yes
step_no: 4000000
seed: no  # randomize if 0 or no

double: no
prioritized: no
shared_bias: yes

# bootstrapping args
# - is_thompson then prob should be 1 (no data mask)
# - if not is_thompson the you definetly need prob < 1 for data bootstrapping
#   else you get just an ensemble
# - vote decides if you evaluate the policy by voting or by mean. You can also
#   evaluate by voting at test time when doing thomspon sampling if vote == yes
boot:
  k: 5
  prob: 1  # no mask if boot_prob == 1
  is_thompson: yes
  vote: yes

linear_size: 128

lr: 0.0001
update_freq: 2
epsilon_steps: 30000
epsilon_end: 0.01
target_update: 1000

learn_start: 10000
mem_size: 100000
log_freq: 10

eval_freq: 100000
eval_steps: 50000
eval_epsilon: 0.01

async_eval: yes
async_memory: yes

mem_device: cuda
pinned_memory: no
