game: frostbite
no_gym: yes
step_no: 50000
seed: no  # randomize if 0 or no

double: no
prioritized: yes
boot_no: 10
boot_prob: .5

lr: 0.00025
update_freq: 4
epsilon_steps: 30000
epsilon_end: 0.1
target_update: 120000
hist_len: 4
hidden_sz: 512
learn_start: 5000
mem_size: 20000
log_freq: 10
learn_log_freq: 5000

eval_freq: 6000
eval_steps: 1500
eval_epsilon: 0.05

async_memory: yes

mem_device: cuda
pinned_memory: no
