game: space_invaders
no_gym: yes
step_no: 100000
seed: no  # randomize if 0 or no

double: yes
prioritized: yes
shared_bias: yes

# bootstrapping args
# - is_thompson then prob should be 1 (no data mask)
# - if not is_thompson the you definetly need prob < 1 for data bootstrapping
#   else you get just an ensemble
# - vote decides if you evaluate the policy by voting or by mean. You can also
#   evaluate by voting at test time when doing thomspon sampling if vote == yes
boot:
  k: 10
  prob: 1  # no mask if boot_prob == 1
  is_thompson: yes
  vote: yes
  var_method: selected_action

linear_size: 512

lr: 0.00025
rmsprop_eps: .01

update_freq: 4
epsilon_steps: 20000
epsilon_end: 0.1
target_update: 10000

learn_start: 3000
mem_size: 10000
log_freq: 1
hist_len: 4
learn_log_freq: 1000

eval_freq: 1000
eval_steps: 200
eval_epsilon: 0.05

async_eval: yes
async_memory: yes

mem_device: cuda
pinned_memory: no